disecto/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from .views import *
from api.views import *
app_name = 'disecto'
urlpatterns = [
    path('', index, name = "Home"),
    path('disecto/productlist/', productlist, name="productlist"),
   
    path('disecto/buyproduct/', buyproduct, name="buyproduct"),
    path('disecto/addproducts/', addproducts, name="addproducts"),
    path('disecto/updateproduct/<str:pk>',updateproduct, name="updateproduct"),
    path('disecto/deleteproduct/<str:pk>', deleteproduct, name="deleteproduct"), 
    path('disecto/orders/', orders, name="orders"),
    path('disecto/updateorders/<str:pk>', updateorders, name="updateorders"),
    path('disecto/deleteorders/<str:pk>', deleteorders, name="deleteorders"), 
   
    path('invoice/', InvoiceListView.as_view(), name="invoice-list"),
    path('create/', createInvoice, name="invoice-create"),
    path('invoice-detail/<id>', view_PDF, name='invoice-detail'),
    path('invoice-download/<id>', generate_PDF, name='invoice-download'),
    #api
    path('api/products/',product_list,name='product_list'),
    path('api/orders/',order_list,name='order_list'),
    path('api/products/<int:pk>',product_detail,name='product_detail'),
    path('api/orders/<int:pk>',order_detail,name='order_list'),
    path('api/invoices/',invoice_list,name='invoice_list'),
    path('api/invoices/<int:pk>',invoice_detail,name='invoice_detail'),

]

task/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("disecto.urls"))
]

disecto/models.py
from django.db import models

# Create your models here.
class Products(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    name= models.CharField(max_length=100)
    description = models.TextField(blank=True,default="")
    price = models.DecimalField(max_digits=7,decimal_places=2)
    quantity_avail = models.IntegerField()
    def __str__(self):
        return f'{self.name}'
class Orders(models.Model):
    
    created = models.DateTimeField(auto_now_add=True)
    product = models.ForeignKey(Products, on_delete= models.SET_NULL, null=True)
    quantity = models.IntegerField()
    def __str__(self):
        
        return f'{self.product}'

class Invoice(models.Model):
    customer = models.CharField(max_length=100)
    customer_email = models.EmailField(null=True, blank=True)
    billing_address = models.TextField(null=True, blank=True)
    date = models.DateField()
    total_amount = models.DecimalField(max_digits=9, decimal_places=2, blank=True, null=True)
    
    def __str__(self):
        return str(self.customer)

class LineItem(models.Model):
    customer = models.ForeignKey(Invoice, on_delete=models.CASCADE)
    service = models.TextField()
    quantity = models.IntegerField()
    rate = models.DecimalField(max_digits=9, decimal_places=2)
    amount = models.DecimalField(max_digits=9, decimal_places=2)

    def __str__(self):
        return str(self.customer)
   

disecto/forms.py
from django import forms
from django.forms import ModelForm,formset_factory
from .models import Invoice,LineItem,Orders,Products

class addproductsForm(ModelForm):
    class Meta:
        model = Products
        fields = '__all__'
class ordersForm(ModelForm):
    class Meta:
        model = Orders
        fields = '__all__'
        
class InvoiceForm(forms.Form):
    
        # fields = ['customer', 'message']
    customer = forms.CharField(
        label='Cusomter',
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'Customer/Company Name',
            'rows':1
        })
    )
    customer_email = forms.CharField(
        label='Customer Email',
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'customer@company.com',
            'rows':1
        })
    )
    billing_address = forms.CharField(
        label='Billing Address',
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': '',
            'rows':1
        })
    )
   

class LineItemForm(forms.Form):
    
    service = forms.CharField(
        label='Service/Product',
        widget=forms.TextInput(attrs={
            'class': 'form-control input',
            'placeholder': 'Service Name'
        })
    )
  
    quantity = forms.IntegerField(
        label='Qty',
        widget=forms.TextInput(attrs={
            'class': 'form-control input quantity',
            'placeholder': 'Quantity'
        }) #quantity should not be less than one
    )
    rate = forms.DecimalField(
        label='Rate $',
        widget=forms.TextInput(attrs={
            'class': 'form-control input rate',
            'placeholder': 'Rate'
        })
    )
    # amount = forms.DecimalField(
    #     disabled = True,
    #     label='Amount $',
    #     widget=forms.TextInput(attrs={
    #         'class': 'form-control input',
    #     })
    # )
    
LineItemFormset = formset_factory(LineItemForm, extra=1)

disecto/views.py
# Create your views here.

from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from .models import LineItem, Invoice,Products,Orders
from .forms import LineItemFormset, InvoiceForm,addproductsForm,ordersForm
from .render import render_to_pdf


def index(request):
    return render(request,'disecto/home.html')
def buyproduct(request):
    form = ordersForm()
    if request.method == 'POST':
        form = ordersForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/disecto/orders')
    context = {'form':form}
    return render(request,'disecto/buyproduct.html',context)
def addproducts(request):
    form = addproductsForm()
    if request.method == 'POST':
       # print(request.POST)
       form = addproductsForm(request.POST)
       if form.is_valid():
           form.save()
           return redirect('/disecto/productlist')
    context = {'form':form}
    return render(request,'disecto/addproducts.html',context)

def updateproduct(request,pk):
    product = Products.objects.get(id=pk)
    if request.method == 'POST':
       # print(request.POST)
       form = addproductsForm(request.POST,instance=product)
       if form.is_valid():
           form.save()
           return redirect('/disecto/productlist')
    form = addproductsForm(instance=product)
    context = {'form':form}
    return render(request,'disecto/updateproduct.html',context)
def updateorders(request,pk):
    order = Orders.objects.get(id=pk)
    if request.method == 'POST':
       # print(request.POST)
       form = ordersForm(request.POST,instance=order)
       if form.is_valid():
           form.save()
           return redirect('/disecto/orders')
    form = ordersForm(instance=order)
    context = {'form':form}
    return render(request,'disecto/updateorders.html',context)
def deleteproduct(request,pk):
    product = Products.objects.get(id=pk)
    if request.method == "POST":
        product.delete()
        return redirect('/disecto/productlist')
    context = {'product':product}
    return render(request,'disecto/deleteproduct.html',context)
def deleteorders(request,pk):
    order = Orders.objects.get(id=pk)
    if request.method == "POST":
        order.delete()
        return redirect('/disecto/orders')
    context = {'order':order}
    return render(request,'disecto/deleteorders.html',context)
def orders(request):
    order = Orders.objects.all()
    context = {'order':order}
    return render(request,'disecto/orders.html',context)

def productlist(request):
    products = Products.objects.all()
    context = {"products":products}
    return render(request,'disecto/productlist.html', context)

class InvoiceListView(View):
    def get(self, *args, **kwargs):
        invoices = Invoice.objects.all()
        context = {
            "invoices":invoices,
        }

        return render(self.request, 'disecto/invoice-list.html', context)
    
    def post(self, request):        
        # import pdb;pdb.set_trace()
        invoice_ids = request.POST.getlist("invoice_id")
        invoice_ids = list(map(int, invoice_ids))

        update_status_for_invoices = int(request.POST['status'])
        invoices = Invoice.objects.filter(id__in=invoice_ids)
        # import pdb;pdb.set_trace()
        if update_status_for_invoices == 0:
            invoices.update(status=False)
        else:
            invoices.update(status=True)

        return redirect('disecto:invoice-list')

def createInvoice(request):
    """
    Invoice Generator page it will have Functionality to create new invoices, 
    this will be protected view, only admin has the authority to read and make
    changes here.
    """

    heading_message = 'Formset Demo'
    if request.method == 'GET':
        formset = LineItemFormset(request.GET or None)
        form = InvoiceForm(request.GET or None)
    elif request.method == 'POST':
        formset = LineItemFormset(request.POST)
        form = InvoiceForm(request.POST)
        
        if form.is_valid():
            invoice = Invoice.objects.create(customer=form.data["customer"],
                    customer_email=form.data["customer_email"],
                    billing_address = form.data["billing_address"],
                    date=form.data["date"],
                   
                    )
            # invoice.save()
            
        if formset.is_valid():
            # import pdb;pdb.set_trace()
            # extract name and other data from each form and save
            total = 0
            for form in formset:
                service = form.cleaned_data.get('service')
                quantity = form.cleaned_data.get('quantity')
                rate = form.cleaned_data.get('rate')
                if service  and quantity and rate:
                    amount = float(rate)*float(quantity)
                    total += amount
                    LineItem(customer=invoice,
                            service=service,
                            
                            quantity=quantity,
                            rate=rate,
                            amount=amount).save()
            invoice.total_amount = total
            invoice.save()
            try:
                generate_PDF(request, id=invoice.id)
            except Exception as e:
                print(f"********{e}********")
            return redirect('disecto:invoice-list')
    context = {
        "title" : "Invoice Generator",
        "formset": formset,
        "form": form,
    }
    return render(request, 'disecto/invoice-create.html', context)


def view_PDF(request, id=None):
    invoice = get_object_or_404(Invoice, id=id)
    lineitem = invoice.lineitem_set.all()

    context = {
        "company": {
            "name": "Disecto",
            "address" :"Sector xn, District, Jammu & Kashmir",
            "phone": "(818) XXX XXXX",
            "email": "contact@disecto.com",
        },
        "invoice_id": invoice.id,
        "invoice_total": invoice.total_amount,
        "customer": invoice.customer,
        "customer_email": invoice.customer_email,
        "date": invoice.date,
        
        "billing_address": invoice.billing_address,
       
        "lineitem": lineitem,

    }
    return render(request, 'disecto/pdf_template.html', context)

def generate_PDF(request, id):
    # Use False instead of output path to save pdf to a variable
    # pdf = pdfkit.from_url(request.build_absolute_uri(reverse('invoice:invoice-detail', args=[id])), False)
    # response = HttpResponse(pdf,content_type='application/pdf')
    # response['Content-Disposition'] = 'attachment; filename="invoice.pdf"'
    # return response
    invoice = get_object_or_404(Invoice, id=id)
    lineitem = invoice.lineitem_set.all()

    context = {
        "company": {
            "name": "Disecto",
            "address" :"Sector xn, District, Jammu & Kashmir",
            "phone": "(818) XXX XXXX",
            "email": "contact@disecto.com",
        },
        "invoice_id": invoice.id,
        "invoice_total": invoice.total_amount,
        "customer": invoice.customer,
        "customer_email": invoice.customer_email,
        "date": invoice.date,
        
        "billing_address": invoice.billing_address,
       
        "lineitem": lineitem,

    }
    return render_to_pdf( 'disecto/pdf_template.html', context)


def view_404(request,  *args, **kwargs):

    return redirect('disecto:invoice-list')

disecto/templates/disecto/addproducts.html
{% extends "disecto/main.html" %}

{% block content %}
    <div style=" 
    width: 100%;
    display: flex;
    flex-direction: row;
    flex-wrap: wrap;
    justify-content: center;
    align-items: center; ">
        <div style="width: 80%;
        border-radius: 15px ;
        height: auto;
        margin: 10px;
        padding: 5px;
        text-align: center;
        background:antiquewhite;
       ">  
       <h3>Add New Products</h3>
       <button class="btn btn-outline-secondary"><a href="/">Home</a></button>
       <button class="btn btn-outline-secondary"><a href="/disecto/productlist/">Product List</a></button>
       <div style="width: 100%;
       display: flex;
       flex-direction: column;
       flex-wrap: wrap;
       justify-content: center;
       align-items: center; ">
            <form method="POST" style="
            width: 40%;
            display: flex;
            flex-direction: column;
            text-align: center;
           
            ">
                {% csrf_token %} 
                {{form}}
                <br />
                <input type="submit" value="Submit">
            </form>
        </div>   
    </div>
    </div>

{% endblock content %}

disecto/templates/disecto/base.html
<!doctype html>{% load static %}
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
     <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
     <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
     <link href="{% static 'css/bulma-calendar.min.css' %}" rel="stylesheet">

     <link href="{% static 'js/bulma-calendar.min.js' %}" rel="stylesheet">
     <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.0/css/bulma.min.css">
     {% block custom_css %}{% endblock %}
    <title>Disecto</title>
</head>
<body>
     
    <div class="container">
                {% block content %}
                {% endblock %}
            </div>
    

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
     {% block custom_js %}{% endblock %}
</body>

disecto/templates/disecto/buyproduct.html
{% extends "disecto/main.html" %}

{% block content %}
    <div style=" 
    width: 100%;
    display: flex;
    flex-direction: row;
    flex-wrap: wrap;
    justify-content: center;
    align-items: center; ">
        <div style="width: 80%;
        border-radius: 15px ;
        height: auto;
        margin: 10px;
        padding: 5px;
        text-align: center;
        background:antiquewhite;
       ">  
       <h3>Buy Products</h3>
       <button class="btn btn-outline-secondary"><a href="/">Home</a></button>
       <button class="btn btn-outline-secondary"><a href="/disecto/addproducts/">Add Products</a></button>
      
       <button class="btn btn-outline-secondary"><a href="/disecto/productlist/">Products List</a></button>
       <div style="width: 100%;
       display: flex;
       flex-direction: column;
       flex-wrap: wrap;
       justify-content: center;
       align-items: center; ">
            <form method="POST" style="
            width: 40%;
            display: flex;
            flex-direction: column;
            text-align: center;
           
            ">
                {% csrf_token %} 
                {{ form }}
                <br />
                <input type="submit" value="Submit">
            </form>
        </div> 
       </div>
    </div>

{% endblock content %}

disecto/templates/disecto/deleteorders.html
{% extends "disecto/main.html" %}


{% block content %}
    <div style=" 
    width: 100%;
    display: flex;
    flex-direction: row;
    flex-wrap: wrap;
    justify-content: center;
    align-items: center; ">
        <div style="width: 80%;
        border-radius: 15px ;
        height: auto;
        margin: 10px;
        padding: 5px;
        text-align: center;
        background:antiquewhite;
       ">  
       <p>Are you sure you want to Delete <i>{{order.name}} </i> </p>
       <form action = "{% url 'disecto:deleteorders' order.id %}"method="POST">
        {% csrf_token %} 
        
        <a href="/">Cancel</a>
        <input type="submit" value="Confirm">
       </form>
    </div>
    </div>

{% endblock content %}

disecto/templates/disecto/deleteproduct.html
{% extends "disecto/main.html" %}


{% block content %}
    <div style=" 
    width: 100%;
    display: flex;
    flex-direction: row;
    flex-wrap: wrap;
    justify-content: center;
    align-items: center; ">
        <div style="width: 80%;
        border-radius: 15px ;
        height: auto;
        margin: 10px;
        padding: 5px;
        text-align: center;
        background:antiquewhite;
       ">  
       <p>Are you sure you want to Delete <i>{{product.name}} </i> </p>
       <form action = "{% url 'disecto:deleteproduct'  product.id %}"method="POST">
        {% csrf_token %} 
        
        <a href="/">Cancel</a>
        <input type="submit" value="Confirm">
       </form>
    </div>
    </div>

{% endblock content %}

disecto/templates/disecto/home.html
{% extends "disecto/main.html" %}

{% block content %}
    <div style=" 
    width: 100%;
    display: flex;
    flex-direction: row;
    flex-wrap: wrap;
    justify-content: center;
    align-items: center; ">
        <div style="width: 80%;
        border-radius: 15px ;
        height: auto;
        margin: 10px;
        padding: 5px;
        margin-top: 20px;
        padding-top: 20px;
        text-align: center;
        background:antiquewhite;
       ">      
        <div>
        <h4 style="margin: 10px;">Website Testing</h4>
            <button type="button" class="btn btn-outline-secondary"><a href="disecto/buyproduct/">Buy Product</a></button>
            <!-- <button type="button" class="btn btn-outline-success"><a href="invoices/invoicetemplate/">Invoice Editor</a></button> -->
            <button type="button" class="btn btn-outline-danger"><a href="disecto/orders/">Orders</a></button>
            <button type="button" class="btn btn-outline-secondary"><a href="disecto/addproducts/">Add Products</a></button>
            <button type="button" class="btn btn-outline-success"><a href="disecto/productlist/">List Products</a></button>
        <h4 style="margin: 10px;">Api Testing</h4>    
            <button type="button" class="btn btn-outline-secondary"><a href="api/products/">Product List</a></button>
            <button type="button" class="btn btn-outline-secondary"><a href="api/invoices/">Invoice List</a></button>

            <button type="button" class="btn btn-outline-secondary"><a href="api/orders/">Orders List</a></button>
        <h4 style="margin: 10px;">Generate Invoice</h4>
           <button class="btn btn-outline-secondary"><a href="invoice/">Invoice List</a></button>
           <button class="btn btn-outline-secondary"><a href="create/">Create New Invoice</a></button>     
        </div>
       </div>
    </div>

{% endblock content %}

disecto/templates/disecto/invoice-list.html
{% extends 'disecto/base.html' %}
{% block content %}
<div class="columns is-centered has-text-centered">
    <div class="column is-half">
        <div class="card has-background-white-ter">
            <h1 class="title is-3"></h1>
        </div>
    </div>
</div>
<form action="{% url 'disecto:invoice-list' %}" method="post">{% csrf_token %}
    <div class="card">
        <header class="card-header">
            <p class="card-header-title">
                All Orders / Change Order Status &nbsp;<button class="button is-rounded is-success">
                    <a href="{% url 'disecto:invoice-create' %}" class="has-text-white">Create Invoice</a></button>
                    <button class="button is-rounded is-info" style="margin-left: 5px;">
                        <a href="{% url 'disecto:Home' %}" class="has-text-white">Home</a></button>
            </p>
        </header>
        <div class="card-content">
            <div class="content">

                <table class="table is-fullwidth is-bordered is-hoverable is-striped">
                    <tbody>
                        <thead>
                            <tr>
                               
                                <th>INVOICE</th>
                                <th>CUSTOMER</th>
                                <th>DATE</th>
                                <th>TOTAL</th>
                                <th>View</th>
                                <th>DOWNLOAD</th>

                            </tr>
                        </thead>
                        {% for invoice in invoices %}
                        <tr>
                            
                            <td width="1%">#{{invoice.id}}</td>
                            <td width="9%">{{invoice.customer}}</td>
                            <td> {{invoice.date}}</td>
                            <td>{{invoice.total_amount}}</td>
                           
                            <td width="1%"><a href="{% url 'disecto:invoice-detail' id=invoice.id %}">
                                <div class="button is-small is-warning">View</div>
                            </a></td>
                            <td width="1%"><a href="{% url 'disecto:invoice-download' id=invoice.id %}">Download</a></td>
                        </tr>
                        {% endfor %}

                    </tbody>
                </table>

            </div>
        </div>
    </div><br /><br /><br />
   
</form>

{% endblock content %}

disecto/templates/disecto/main.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">

    <title>
       Disecto
    </title>
    <style>
      a{
        text-decoration: none;
      }
      a:hover{
        color: white;
      }
    </style>
  </head>
  <body>
   {% block content %} {% endblock %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ" crossorigin="anonymous"></script>  
    <!-- <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js" integrity="sha384-W8fXfP3gkOKtndU4JGtKDvXbO53Wy8SZCQHczT5FMiiqmQfUpWbYdTil/SxwZgAN" crossorigin="anonymous"></script> -->
    <!-- <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.min.js" integrity="sha384-skAcpIdS7UcVUC05LJ9Dxay8AXcDYfBJqt1CJ85S/CFujBsIzCIv+l9liuYLaMQ/" crossorigin="anonymous"></script> -->
   
  </body>
</html>

disecto/templates/disecto/orders.html
{% extends "disecto/main.html" %}

{% block content %}
    <div style=" 
    width: 100%;
    display: flex;
    flex-direction: row;
    flex-wrap: wrap;
    justify-content: center;
    align-items: center; ">
        <div style="width: 80%;
        border-radius: 15px ;
        height: auto;
        margin: 10px;
        padding: 5px;
        text-align: center;
        background:antiquewhite;
       ">  
       <h3>Orders</h3>
       <button class="btn btn-outline-secondary"><a href="/">Home</a></button>
       <button class="btn btn-outline-secondary"><a href="/disecto/productlist/">Product List</a></button>
       <button class="btn btn-outline-secondary"><a href="/disecto/buyproduct/">Buy Product</a></button>
       <table class="table">
        <thead>
          <tr>
            <th scope="col">ID(Key)</th>
            <th scope="col">Name</th>
            <th scope="col">Price</th>
            <th scope="col">Quantity Available</th>
            <th scope="col">Edit</th>
          </tr>
        </thead>
        <tbody>
            {% for i in order %}
          <tr>
            <th scope="row">{{i.id}}</th>
            <td>{{ i.product }}</td>
            
            <td>{{i.product.price}}</td>
            <td>{{i.quantity}}</td> 
            <td><button  class="btn btn-secondary"><a href="{% url 'disecto:updateorders' i.id%}">Update</a></button>
            <button class="btn btn-danger"><a href="{% url 'disecto:deleteorders' i.id%}">Delete</a></button></td>
          </tr>
          {% endfor%}
        </tbody>
      </table>  
       
       </div>
    </div>

{% endblock content %}

disecto/templates/disecto/pdf_template.html
<!DOCTYPE html>{% load static%}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="{%static 'css/invoice-template-1.css' %}" media="all" />
  </head>
  <body>
    <header class="clearfix">
      <div id="logo">
        <img src="{% static 'img/logo.png'%}" style="width: 134px; height:116px"> 
      </div>
      <div id="company">
        <h1 class="name">{{company.name}}</h1>
        <div>{{company.address}}</div>
        <div>{{company.phone}}</div>
        <div><a href="mailto:{{company.email}}">{{company.email}}</a></div>
      </div>
      </div>
    </header>
    <main>
      <div id="details" class="clearfix">
        <div id="client">
          <div class="to">INVOICE TO:</div>
          <h2 class="name">{{customer}}</h2>
          <div class="address">{{billing_address}}</div>
          <div class="email"><a href="mailto:{{customer_email}}">{{customer_email}}</a></div>
        </div>
        <div id="invoice">
          <h1>#{{invoice_id}}</h1>
          <div class="date">Date of Invoice: {{date}}</div>
         
        </div>
      </div>
      <table border="0" cellspacing="0" cellpadding="0">
        <thead>
          <tr>
            <th class="no">#</th>
            <th class="desc"></th>
            <th class="unit">RATE</th>
            <th class="qty">QUANTITY</th>
            <th class="total">TOTAL</th>
          </tr>
        </thead>
        <tbody>
			{% for item in lineitem %}
          <tr>
            <td class="no">{{forloop.counter}}</td>
            <td class="desc"></td>
            <td class="unit">${{item.rate}}</td>
            <td class="qty">{{item.quantity}}</td>
            <td class="total">${{item.amount}}</td>
		  </tr>
		  {% endfor %}
        </tbody>
        <tfoot>
          <tr>
            <td colspan="2"></td>
            <td colspan="2">SUBTOTAL</td>
            <td>${{invoice_total}}</td>
          </tr>
          <tr>
            <td colspan="2"></td>
            <td colspan="2">TAX 0%</td>
            <td>${{invoice_total}}</td>
          </tr>
          <tr>
            <td colspan="2"></td>
            <td colspan="2">GRAND TOTAL</td>
            <td>${{invoice_total}}</td>
          </tr>
        </tfoot>
      </table>
      <div id="thanks">Thank you!</div>
      <div id="notices">
        
    </main>
 
  </body>
</html>

disecto/templates/disecto/productlist.html
{% extends "disecto/main.html" %}

{% block content %}
    <div style=" 
    width: 100%;
    display: flex;
    flex-direction: row;
    flex-wrap: wrap;
    justify-content: center;
    align-items: center; ">
        <div style="width: 80%;
        border-radius: 15px ;
        height: auto;
        margin: 10px;
        padding: 5px;
        text-align: center;
        background:antiquewhite;
       ">  
       <h3>List Of Products Available</h3>
       <button class="btn btn-outline-secondary"><a href="/">Home</a></button>
       <button class="btn btn-outline-secondary"><a href="/disecto/buyproduct/">Buy Products</a></button>
       <button class="btn btn-outline-secondary"><a href="/disecto/addproducts/">Add Products</a></button>
       <table class="table">
        <thead>
          <tr>
            <th scope="col">ID(Key)</th>
            <th scope="col">Name</th>
            <th scope="col">Price</th>
            <th scope="col">Quantity Available</th>
            <th scope="col">Edit</th>
          </tr>
        </thead>
        <tbody>
            {% for i in products%}
          <tr>
            <th scope="row">{{i.id}}</th>
            <td>{{i.name}}</td>
            
            <td>{{i.price}}</td>
            <td>{{i.quantity_avail}}</td> 
            <td><button  class="btn btn-secondary"><a href="{% url 'disecto:updateproduct' i.id%}">Update</a></button>
            <button class="btn btn-danger"><a href="{% url 'disecto:deleteproduct' i.id%}">Delete</a></button></td>
        
          </tr>
          {% endfor%}
        </tbody>
      </table>    
       
        
       
       </div>
    </div>

{% endblock content %}

disecto/templates/disecto/updateorders.html
{% extends "disecto/main.html" %}
{% block content %}
    <div style=" 
    width: 100%;
    display: flex;
    flex-direction: row;
    flex-wrap: wrap;
    justify-content: center;
    align-items: center; ">
        <div style="width: 80%;
        border-radius: 15px ;
        height: auto;
        margin: 10px;
        padding: 5px;
        text-align: center;
        background:antiquewhite;
       ">  
       <h3>Buy Products</h3>
       <button class="btn btn-outline-secondary"><a href="/">Home</a></button>
       <button class="btn btn-outline-secondary"><a href="/disecto/productlist/">Products List</a></button>
       <div style="width: 100%;
       display: flex;
       flex-direction: column;
       flex-wrap: wrap;
       justify-content: center;
       align-items: center; ">
            <form method="POST" style="
            width: 40%;
            display: flex;
            flex-direction: column;
            text-align: center;
           
            ">
                {% csrf_token %} 
                {{ form }}
                <br />
                <input type="submit" value="Submit">
            </form>
        </div> 
       </div>
    </div>

{% endblock content %}